[package]
name = "signaling-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
clap = {version = "4.0.15", features=["derive"]}
tokio = "1.21.2"
webrtc = "0.5.1"
